### ISSUE TITLE
Add TOR support

### ISSUE THREAD

**Issue by nikriek** [jafrewa/JodelPy#5]
This can be done using the requesocks package: 
https://gist.github.com/jefftriplett/9748036

**Comment by jafrewa** [comment]
Can you do a PR for it ?

**Comment by nikriek** [comment]
Jup. Should I add an --anonymous argument for each script?

**Comment by jafrewa** [comment]
Maybe --tor ?

**Comment by nikriek** [comment]
👍

**Comment by nikriek** [comment]
https://github.com/jafrewa/JodelPy/pull/6
